// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Lets = require("./Lets.bs.js");

var nav = Lets.Async[/* let_ */1](fetch("/data/meta.json", { }), (function (response) {
        return response.json();
      }));

exports.nav = nav;
/* nav Not a pure module */
