// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Lets = require("./Lets.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

function getItem(l, key) {
  return l.getItem(key);
}

function setItem(l, key, v) {
  return l.setItem(key, v);
}

function getAll(l, getId) {
  return Lets.Async[/* let_ */1](l.keys(), (function (keys) {
                return Lets.Async[/* let_ */1](Promise.all(Belt_Array.map(keys, (function (key) {
                                      return l.getItem(key);
                                    }))), (function (allItems) {
                              return Lets.Async[/* resolve */2](Belt_MapString.fromArray(Belt_Array.map(allItems, (function (item) {
                                                    return /* tuple */[
                                                            Curry._1(getId, item),
                                                            item
                                                          ];
                                                  }))));
                            }));
              }));
}

exports.getItem = getItem;
exports.setItem = setItem;
exports.getAll = getAll;
/* No side effect */
