// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var Annotation = /* module */Block.localModule([], []);

var Tag = /* module */Block.localModule([], []);

exports.Annotation = Annotation;
exports.Tag = Tag;
/* No side effect */
